-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: /home/greg/Projects/Phpstorm/mediawiki-extensions-ATBridge/sql/central_tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE atproto_users (
  at_uniq SERIAL NOT NULL,
  at_wiki TEXT NOT NULL,
  at_platform TEXT NOT NULL,
  at_platform_uniq INT NOT NULL,
  at_handle TEXT DEFAULT NULL,
  at_domain TEXT DEFAULT NULL,
  at_email TEXT NOT NULL,
  at_passcode TEXT NOT NULL,
  PRIMARY KEY(at_uniq)
);

CREATE UNIQUE INDEX per_wiki_user ON atproto_users (
  at_wiki, at_platform, at_platform_uniq
);

CREATE INDEX at_wiki ON atproto_users (at_wiki);


CREATE TABLE atproto_optin (
  opt_account INT NOT NULL,
  opt_key TEXT NOT NULL,
  opt_value SMALLINT NOT NULL,
  PRIMARY KEY(opt_account, opt_key)
);

CREATE INDEX opt_account ON atproto_optin (opt_account);
