-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: /home/greg/Projects/Phpstorm/mediawiki-extensions-ATBridge/sql/central_tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/atproto_users (
  at_uniq INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  at_wiki BLOB NOT NULL, at_platform BLOB NOT NULL,
  at_platform_uniq INTEGER UNSIGNED NOT NULL,
  at_handle BLOB NOT NULL, at_domain BLOB DEFAULT NULL,
  at_email BLOB NOT NULL, at_passcode BLOB NOT NULL
);

CREATE UNIQUE INDEX per_wiki_user ON /*_*/atproto_users (
  at_wiki, at_platform, at_platform_uniq
);

CREATE INDEX at_wiki ON /*_*/atproto_users (at_wiki);


CREATE TABLE /*_*/atproto_optin (
  opt_account INTEGER UNSIGNED NOT NULL,
  opt_key BLOB NOT NULL,
  opt_value SMALLINT NOT NULL,
  PRIMARY KEY(opt_account, opt_key)
);

CREATE INDEX opt_account ON /*_*/atproto_optin (opt_account);
