-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: /home/greg/Projects/Phpstorm/mediawiki-extensions-ATBridge/sql/local_tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/atproto_post (
  post_account INTEGER UNSIGNED NOT NULL,
  post_user INTEGER DEFAULT NULL
);
